### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '&'

### ISSUE THREAD

**Issue by abdullahsayed4131** [rinvex/laravel-widgets#13]
![Capture](https://user-images.githubusercontent.com/37441843/103488843-1d32c880-4e36-11eb-970d-a582d9aa9890.JPG)
&lt;script&gt;
    var widgetTimer000000007368bf79000000005cdf1fb6 = setInterval(function () {
        if (window.$) {
            $(&#039;#rinvex-widgets-container-000000007368bf79000000005cdf1fb6&#039;).load(&#039;http://localhost/example/widget?id=000000007368bf79000000005cdf1fb6&amp;amp;params=eyJpdiI6ImpocUVCRldPT3VHUzFQaVdDVU11VkE9PSIsInZhbHVlIjoiSnF2TVA0T3VMemxxb1p3ditMdldDU0U5cU5DTXBWcWVRREMwL1ZiM1ZRMD0iLCJtYWMiOiIzZWU0NjI1MzNjZGIzNWRhZjY2ZjdjMjU2MGYzZmY4YWNlOGQ1ZTY0MGQwMDBlMzNmYzA0ZjJmYjBjZDM0NDMzIn0%3D&#039;);
            clearInterval(widgetTimer000000007368bf79000000005cdf1fb6);
        }
    }, 100);
&lt;/script&gt;

**Comment by Omranic** [comment]
Thank you for reporting this, it's fixed now https://github.com/rinvex/laravel-widgets/commit/7882ddb190ed5d38bb264081f403b8bc6960dd7d

I'll tag a new release later 👍
