### ISSUE TITLE
WidgetMakeCommand.php missing "/"

### ISSUE THREAD

**Issue by joe-hagerty** [rinvex/laravel-widgets#5]
Installed and tried to create a widget.  Got error stating stub could not be found.
Works with:

line 39:
` return __DIR__.'../../../resources/stubs/widget.stub';`

changed to:
` return __DIR__.'/../../../resources/stubs/widget.stub';`

**Comment by Omranic** [comment]
Thank you, fixed in 9d47f690fb22ba8f230c719292e2a322aa015340
