### ISSUE TITLE
Trait 'Rinvex\Support\Traits\ConsoleTools' not found  

### ISSUE THREAD

**Issue by ou-pas** [rinvex/laravel-widgets#6]
Hello, after composer require,

`In WidgetsServiceProvider.php line 16:`
`Trait 'Rinvex\Support\Traits\ConsoleTools' not found`

and on  artisan make:widget RecentPosts  

`Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined method Rinvex\Widgets\Providers\WidgetsServiceProvider::publishesViews()
`

Edit : require error on master, ok on develop

**Comment by Omranic** [comment]
Thank you for reporting this, it's now fixed on both `develop` and `master`, check new release [v3.0.1](https://github.com/rinvex/laravel-widgets/tree/v3.0.1)
