### ISSUE TITLE
Laravel 7

### ISSUE THREAD

**Issue by nasirkhan** [rinvex/laravel-widgets#9]
I tried t install this package with one of my projects. But install failed with the following error, 

``` 
rinvex/laravel-widgets v3.0.0 requires illuminate/view ^6.0.0 -> satisfiable by laravel/framework[6.x-dev]
```

**Comment by Omranic** [comment]
Latest release v4.x already supports Laravel v7.x but also requires PHP v7.4 as a minimum.
